name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
        working-directory: ./back
      - run: npm test
        working-directory: ./back

  buildback:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch My Node.js Back
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
        working-directory: ./back
      - run: npm run build --if-present
        working-directory: ./back

  pushback:
    needs: buildback
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/priceapi:latest
